version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=nimbus
      - POSTGRES_PASSWORD=nimbus
      - POSTGRES_DB=nimbus
    volumes:
      - nimbus-postgres-data:/var/lib/postgres/data
    ports:
      - 54320:5432

  ws:
    image: nimbus-ws
    working_dir: /nimbus
    volumes:
      - ./nimbus-service:/nimbus
    ports:
      - 9000:9000
    environment:
      DATABASE_URL: "jdbc:postgresql://db:5432/nimbus?user=nimbus&password=nimbus"
    command: sbt -Dconfig.resource=application.conf web/run

volumes:
  nimbus-postgres-data:
